#include "gpio.h"

void I2cPins(void)
{
	//B6 - SCL, B7 - SDA

	//Turn on clock for port B
	if (!(RCC->AHBENR & RCC_AHBENR_GPIOBEN))
	{
		RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
	}

	//alternate function
	GPIOB->MODER &= ~(GPIO_MODER_MODER6 | GPIO_MODER_MODER7);
	GPIOB->MODER |= (GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1);

	//open-drain
	GPIOB->OTYPER &= ~(GPIO_OTYPER_OT_6 | GPIO_OTYPER_OT_7);
	GPIOB->OTYPER |= (GPIO_OTYPER_OT_6 | GPIO_OTYPER_OT_7);

	//high speed
	GPIOB->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR6 | GPIO_OSPEEDER_OSPEEDR7);
	GPIOB->OSPEEDR |= (GPIO_OSPEEDER_OSPEEDR6 | GPIO_OSPEEDER_OSPEEDR7);

	//pull-up
	GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR6 | GPIO_PUPDR_PUPDR7);
	GPIOB->PUPDR |= (GPIO_PUPDR_PUPDR6_0 | GPIO_PUPDR_PUPDR7_0);

	//AF4 = I2C
	GPIOB->AFR[0] &= ~(GPIO_AFRL_AFRL6 | GPIO_AFRL_AFRL7);
	GPIOB->AFR[0] |= (0x4 << GPIO_AFRL_AFRL6_Pos) | (0x4 << GPIO_AFRL_AFRL7_Pos);

}

void Uart2Pins(void) //uart to PC
{
	//A2 - TX, A3 - RX

	//Turn on clock for port A
	if (!(RCC->AHBENR & RCC_AHBENR_GPIOAEN))
	{
		RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	}

	//alternate function
	GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3);
	GPIOA->MODER |=  (GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1);

	//push-pull
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_2 | GPIO_OTYPER_OT_3);

	//high speed
	GPIOA->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR2 | GPIO_OSPEEDER_OSPEEDR3);
	GPIOA->OSPEEDR |=  (GPIO_OSPEEDER_OSPEEDR2 | GPIO_OSPEEDER_OSPEEDR3);

	//PA2 no-pull, PA3 pull-up
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR2 | GPIO_PUPDR_PUPDR3);
	GPIOA->PUPDR |=  (GPIO_PUPDR_PUPDR3_0);

	//AF7 = UART
	GPIOA->AFR[0] &= ~(GPIO_AFRL_AFRL2 | GPIO_AFRL_AFRL3);
	GPIOA->AFR[0] |=  (0x7 << GPIO_AFRL_AFRL2_Pos) | (0x7 << GPIO_AFRL_AFRL3_Pos);
}

void Uart1Pins(void) //uart to GPS
{
	//Turn on clock for port A
	if (!(RCC->AHBENR & RCC_AHBENR_GPIOAEN))
	{
		RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	}

	//Alternate Function
	GPIOA->MODER &= ~(GPIO_MODER_MODER9 | GPIO_MODER_MODER10);
	GPIOA->MODER |=  (GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1);

	//Push-Pull
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT_9 | GPIO_OTYPER_OT_10);

	//High speed
	GPIOA->OSPEEDR |=  (GPIO_OSPEEDER_OSPEEDR9 | GPIO_OSPEEDER_OSPEEDR10);

	////PA9 no-pull, PA10 pull-up
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR9 | GPIO_PUPDR_PUPDR10);
	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR10_0;

	//AF7 = UART
	GPIOA->AFR[1] &= ~(GPIO_AFRH_AFRH1 | GPIO_AFRH_AFRH2);
	GPIOA->AFR[1] |=  ((0x7 << GPIO_AFRH_AFRH1_Pos) | (0x7 << GPIO_AFRH_AFRH2_Pos));
}

















