M48
; DRILL file {KiCad 9.0.8} date 2026-03-18T19:29:43+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-18T19:29:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X149.1Y-88.875
X149.1Y-94.655
T2
X145.5Y-75.0
X145.5Y-144.5
X219.5Y-75.0
X219.5Y-144.5
M30
